# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-28 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_comment'),
        ('comments', '0002_comment_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Blog'),
        ),
    ]
