# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-28 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_comment_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='blog_id',
            field=models.IntegerField(null=True),
        ),
    ]
